project:
  type: website
  
  render:
    - index.qmd
    - undervisningsplan.qmd
    - lectures/01a_forberedelser.qmd
    - lectures/01c_øvelse.qmd
    - lectures/01b1_slides.qmd
    - lectures/llm/index.qmd
    - lectures/llm/llm_01_pandas.qmd
    - lectures/llm/llm_02_linreg.qmd
    - lectures/llm/llm_03_logreg.qmd
    - lectures/llm/llm_04_kryssvalidering.qmd
    - lectures/llm/llm_05_beslutningstraer.qmd
    - lectures/llm/hon2110_oppfrisking.qmd
    - lectures/02a_forberedelser.qmd
    - lectures/02b_slides.qmd
    - lectures/02c_øvelse.qmd
    - lectures/03a_forberedelser.qmd
    - lectures/03b_slides.qmd
    - lectures/03b2_tutorial.qmd
    - lectures/04a_forberedelser.qmd
    - lectures/04b_slides.qmd
    - lectures/etikk_01a_forberedelser.qmd
    - lectures/etikk_02a_forberedelser.qmd
    - lectures/05a_forberedelser.qmd
    - lectures/05b_slides_ane.qmd
    # - lectures/05c_øvelse.qmd
    # - lectures/06a_forberedelser.qmd
    - lectures/06_slides_ane.qmd
    # - lectures/07a_forberedelser.qmd
    # - lectures/07b_slides.qmd
    - oppgaver/oblig_titanic.qmd
    # - oppgaver/oblig_strompris/oblig_strompris.qmd


website:
  title: "HON2200 – V2026"
  favicon: hon_logo.svg

  sidebar:
    style: "docked"
    search: true
    title: HON2200 – V2026

    contents:
      - section: "Kursinformasjon" # Chapter Group Title
        href: index.qmd # File for Chapter 1 (Part I)
        contents: # Sub-sections within Part I
          - index.qmd # File for Chapter 1 (Part I)
          - undervisningsplan.qmd
      - section: "Del 1: Statistikk" # Chapter Group Title
        href: lectures/01a_forberedelser.qmd # File for Chapter 1 (Part I)
        contents: # Sub-sections within Part I
          - section : "Uke 1 – 23. januar"
            href: lectures/01a_forberedelser.qmd # File for Chapter 1 (Part I)
            contents:
              - lectures/01a_forberedelser.qmd # File for Chapter 1 (Part I)
              - lectures/01b1_slides.qmd
              - lectures/llm/hon2110_oppfrisking.qmd
              - lectures/01c_øvelse.qmd
          #    - lectures/01c_øvelse_nosol.qmd
          - section: "Uke 2 – 30. januar"
            href: lectures/02a_forberedelser.qmd # File for Chapter 2 (Part II)
            contents:
              - lectures/02a_forberedelser.qmd # File for Chapter 2 (Part II)
              - lectures/02b_slides.qmd
              - lectures/02c_øvelse.qmd
          #    - lectures/02c_øvelse_nosol.qmd
          - section: "Uke 3 – 7. februar"
            href: lectures/03a_forberedelser.qmd # File for Chapter 2 (Part II)
            contents:
              - lectures/03a_forberedelser.qmd # File for Chapter 2 (Part II)
              - lectures/03b_slides.qmd
              - lectures/03b2_tutorial.qmd
          - section: "Uke 4 – 14. februar"
            href: lectures/04a_forberedelser.qmd # File for Chapter 2 (Part II)
            contents:
              - lectures/04a_forberedelser.qmd # File for Chapter 2 (Part II)
              - lectures/04b_slides.qmd
          - section: "Uke 7 – 6. mars"
            href: lectures/05a_forberedelser.qmd
            contents:
              - lectures/05a_forberedelser.qmd
              - lectures/05b_slides_ane.qmd

          - section: "Uke 8 – 13. mars"
            href: lectures/06a_forberedelser.qmd
            contents:
              - lectures/06a_forberedelser.qmd
              - lectures/06_slides_ane.qmd
          # - section: "Uke 9 – 20. mars"
          #   href: lectures/07a_forberedelser.qmd
          #   contents:
          #     - lectures/07a_forberedelser.qmd
          #     - lectures/07b_slides.qmd

      - section: "Del 2: Digital etikk" # Chapter Group Title
        contents:
          - section: "Uke 5 – 20. februar"
            href: lectures/etikk_01a_forberedelser.qmd
            contents:
              - lectures/etikk_01a_forberedelser.qmd
          - section: "Uke 6 – 27. februar"
            href: lectures/etikk_02a_forberedelser.qmd
            contents:
              - lectures/etikk_02a_forberedelser.qmd

      - section: "Del 3: Oblig og prosjekt"
        contents:
          - oppgaver/oblig_titanic.qmd
      #     - oppgaver/oblig_strompris/oblig_strompris.qmd
      #     - oppgaver/prosjekt_1_compas.qmd
      #     - oppgaver/prosjekt_2.qmd

      - section: "LLM-supplement"
        contents:
          - lectures/llm/index.qmd
          - lectures/llm/llm_01_pandas.qmd
          - lectures/llm/llm_02_linreg.qmd
          - lectures/llm/llm_03_logreg.qmd
          - lectures/llm/llm_04_kryssvalidering.qmd
          - lectures/llm/llm_05_beslutningstraer.qmd
      #     - lectures/llm/llm_06_ensemble.qmd
      #     - lectures/llm/llm_07_onehot.qmd
      #     - lectures/llm/llm_ai_assistert_koding.qmd
      #     - section: "Video-materiale"
      #       contents:
      #         - lectures/llm/video_kryssvalidering_kode.qmd

      # - section: "Endringslogg (kun for utvikling)"
      #   contents:
      #     - endringslogg/v26_planlegging.md
      #     - endringslogg/anbefalinger_v26_og_fremover.md
      #     - section: "Endringer"
      #       contents:
      #         - endringslogg/endringer/2026-01-16_v26_oppstart.md
      #     - section: "Evalueringer"
      #       contents:
      #         - endringslogg/evalueringer/evaluering_v25.md

execute:
  freeze: auto
  error: true
  warning: false

format:
  html:
    theme:
      - flatly
      - custom.css
    toc: true
    toc-location: right
    number-sections: false
    fontcolor: black
    show-notes: false
    code-copy: true
    code-overflow: wrap
    mainfont: system-ui

exercise_solutions:
  week_01: true
  week_02: true
  week_03: true
  week_04: true

filters:
  - remove-notes.lua